# Blog info
blog_name: pandaian
slogan: Be fine, be kind.
url: https://i.pandaian.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: pandaian,熊猫君,熊猫君的博客,PANDA,IAN

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: false #在新页面打开
  - name: Github
    url: https://github.com/pandaian
    target_blank: true
  - name: Bilibili
    url: https://space.bilibili.com/78015298
    target_blank: true

# config page nav
page_nav:
  - name: Blog
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: Cgy
    url: /category/
    target_blank: false
  - name: Tag
    url: /tag/
    target_blank: false
  - name: Link
    url: /link/
    target_blank: false
  - name: Abt
    url: /about/
    target_blank: false
  - name: Srch
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: Box

search_slogan:
  isShow: true # true|fase
  text: You can find the bug of world.

link_slogan:
  isShow: true # true|fase
  text: Add your link i@pandaian.com


# set backtop show or hide
backtop:
  home: false
  archive: true
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: SUPPORT
  tip: Payment QR Code
  items:
    - type: WeChat
      text: WeChat
      imgUrl: /images/WeChat.png
    - type: PayPal
      text: PayPal
      imgUrl: /images/PayPal.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 

# Comment service
# disqus_shortname: pandaian
# gitalk_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
#uyan_key:

# changyan_appid:
# changyan_appkey:

# gitment comment service
# gitment:
#     on: false  # true | false  这里开启
#     owner: # Your GitHub ID. Required.
#     repo: # The repository to store your comments. Make sure you're repo's owner. Required.
#     oauth: # An object contains your client ID and client secret. Required.
#         client_id: # GitHub client ID. Required.
#         client_secret: # GitHub client secret. Required.
#     id: # An optional string to identify your page. Default location.href.
#     title: # An optional title for your page, used as issue's title. Default document.title.
#     link: # An optional link for your page, used in issue's body. Default location.href.
#     desc: # An optional description for your page, used in issue's body. Default ''.
#     labels: # An optional array of labels your want to add when creating the issue. Default [].
#     theme: # An optional Gitment theme object. Default gitment.defaultTheme.
#     perPage: # An optional number to which comments will be paginated. Default 20.
#     maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # 如果使用valine，请设置改之为true
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size




# 不算子,文章访问量统计和显示
busuanzi: false

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "IAN"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "pandaian"
    text_value_url: https://github.com/pandaian
  - type: mail
    icon: icon-mail
    text_key: Mail
    text_value: "i@pandaian.com"
    text_value_url: mailto:i@pandaian.com
  - type: location
    icon: icon-location
    text_key: Location
    text_value: "Anqing"
    text_value_url: https://www.google.com/maps/place/30%C2%B031'55.2%22N+117%C2%B006'55.3%22E/@25.3472907,126.4059474,3z/data=!4m5!3m4!1s0x0:0x0!8m2!3d30.532!4d117.11535

link:
  - name: 织网
    info: 身体和灵魂，总有一个在路上
    url: http://zheng-ji.info/
    avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100
  - name: Dongyado
    info: 生命不止，折腾不息
    url: http://dongyado.com/
    avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=100
  - name: OrangeCoder
    info: android ffmpeg nodejs gradle
    url: http://orangecoder.com/
    avatar: https://avatars0.githubusercontent.com/u/2263785?v=3&s=100
  - name: EverET
    info: 好记性不如烂笔头
    url: http://everet.org/about-me/
    avatar: https://avatars1.githubusercontent.com/u/1559563?v=3&s=100
  - name: 题叶
    info: FP, GUI, Writing
    url: http://tiye.me/
    avatar: https://avatars2.githubusercontent.com/u/449224?v=3&s=100
  - name: McChen
    info: Stay Hungry, Stay Foolish
    url: http://mcchen.club/
    avatar: https://avatars0.githubusercontent.com/u/8033333?v=3&s=100


project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  - type: personal
    name: beside
    url: https://github.com/forsigner/beside
    intro: I need you beside me
  - type: personal
    name: magic-check
    url: https://github.com/forsigner/magic-check
    intro: Beautify Radio and Checkbox with pure CSS
  - type: personal
    name: nice-bar
    url: https://github.com/forsigner/nice-bar
    intro: A nice and lightweight scrollbar
  - type: personal
    name: angular-nice-bar
    url: https://github.com/forsigner/angular-nice-bar
    intro: A nice and lightweight scrollbar in Angular
  - type: personal
    name: fo-popover
    url: https://github.com/forsigner/fo-popover
    intro: A nice popover for Angular
  - type: personal
    name: fo-tooltip
    url: A nice tooltip for Angular
    intro: https://github.com/forsigner/fo-tooltip
  - type: personal
    name: fo-modal
    url: https://github.com/forsigner/fo-modal
    intro: A nice modal for Angular
  - type: personal
    name: mocer
    url: https://github.com/forsigner/mocer
    intro: Setup a mock server easily
  - type: personal
    name: node-pngdefry
    url: https://github.com/forsigner/node-pngdefry
    intro: Repairing iPhone fried PNGs using Node.js
  - type: personal
    name: ng-simditor
    url: https://github.com/forsigner/ng-simditor
    intro: Angular directive for simditor
